### PR TITLE
Use new .spec file for buildozer

### LINKED ISSUE #255: update buildozer spec editor
The current buildozer spec editor works in the old buildozer.spec file. This need to be updated to the latest version.

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
Closes #255

### CODE REVIEW

**Comment by aron-bordin** [comment]
Hi @KeyWeeUsr , thank you for the contribution.
We also need to update the https://github.com/kivy/kivy-designer/tree/master/designer/data/settings buildozer's related settings here ^ to make this UI editor consistent with the spec. 

Just check the new buildozer.spec fields and add them to the configs.

**Comment by KeyWeeUsr** [comment]
I hope I got it right. ^^

**Comment by manthansharma** [comment]
@KeyWeeUsr Update to new buildozer.spec as it has been changed, Since last update of this PR.

**Comment by KeyWeeUsr** [comment]
Added the new properties `android.arch` and `p4a.hook` too. :)

**Comment by aron-bordin** [comment]
@KeyWeeUsr good job, thank  you for this contribution :)

**Pull request merged**
