### PR TITLE
Add New Project Wizard

### LINKED ISSUE #260: New Project Wizard
Implement a new "New Project" dialog, integrate with the buildozer.spec.

The new interface should allow:
- package name
- app name
- version
- initial template (like we have now)
- etc

### PR DESCRIPTION
**Pull request by manthansharma**
Closes #260 
Also, update default.spec to newer version

screen shot 2017-02-14 at 11 43 41 pm

### CODE REVIEW

**Comment by aron-bordin** [comment]
HI @manthansharma thanks for the PR.

Please, just remove the default.spec from this PR. There is another pull request updating it (https://github.com/kivy/kivy-designer/pull/274).

**Comment by manthansharma** [comment]
@aron-bordin I have to update default.spec in this PR as we are changing buildozer.spec with our app variable such as `app_name, package_name,..` for every project and for this i have to customise default.spec.

**Comment by aron-bordin** [comment]
@manthansharma hmm, ok. Sorry, I didn't read the code. I'll review the @KeyWeeUsr PR today, if it's ok you can use that. Just give me a few hours :)

**Comment by aron-bordin** [comment]
@manthansharma I asked some modifications on @KeyWeeUsr 's PR. Let's wait :D

**Comment by KeyWeeUsr** [comment]
@aron-bordin are you sure? I made the changes in #274 already a few days ago. I didn't get any notification.

**Comment by aron-bordin** [comment]
@KeyWeeUsr forgot to start the review :P it's available now :) Just some small changes in the jsons

**Comment by aron-bordin** [comment]
@manthansharma the @KeyWeeUsr 's pr is merged. Please, just rebase this branch and update the PR.

**Comment by manthansharma** [comment]
@aron-bordin Rebase the PR. Mergeable

**Comment by aron-bordin** [comment]
thanks @manthansharma, good work ;)

**Pull request merged**
